### ISSUE TITLE
epubtools-frontend on osx

### ISSUE THREAD

**Issue by mrchristian** [transpect/epubtools-frontend#2]
hi

any ideas why on osx 12.12.5 I might get the following error when running the epubconvert script.

mrcs-MBP:epubtools-frontend mrchristian$ ./epubconvert -d epubtools/sample/sample.html

error

QUOTE

mrcs-MBP:epubtools-frontend mrchristian$ ./epubconvert -d epubtools/sample/sample.html
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
./epubconvert: line 31: cd: : No such file or directory
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
usage: mkdir [-pv] [-m mode] directory ...
readlink: illegal option -- f
usage: readlink [-n] [file ...]
ERROR: input file not found: /epubtools/sample/epub-config.xml

END

Many thanks

Simon

**Comment by gimsieke** [comment]
readlink -f isn't available on OSX. Until we fix this script, copy the definition of real_dir from https://github.com/transpect/calabash-frontend/blob/master/calabash.sh#L10 into the script and use this function instead of readlink -f.

**Comment by mrchristian** [comment]
Hi,

Thank you for the pointer, very much appreciated.
Being a little unsure about exactly which bit should be replaced, can I ask for a little further advice.

Thanks

Simon

Should I replace the whole section in 'epubtools-frontend'

https://github.com/transpect/epubtools-frontend/blob/master/epubconvert#L31

DIR="$( cd -P "$(dirname $( readlink -f "$0" ))" && pwd )"
PWD=$(readlink -f .)
CALABASH=$DIR/calabash/calabash.sh
HEAP=1024m

with the 'calabash-frontend' section

https://github.com/transpect/calabash-frontend/blob/master/calabash.sh#L10

line 9 to 72

# readlink -f is unavailable on Mac OS X
function real_dir() {
    SOURCE="$1"
    while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
	DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
	SOURCE="$(readlink "$SOURCE")"
	[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
    done
    echo "$( cd -P "$( dirname "$SOURCE" )" && pwd  )"
}

DIR="$( real_dir "${BASH_SOURCE[0]}" )"

EXT_BASE=$DIR/extensions

DISTRO="$DIR/distro"

if [ -z "$PROJECT_DIR" ]; then
  PROJECT_DIR=$( real_dir "$DIR" )
fi

# try the legacy name for adaptations first:
if [ -z "$ADAPTATIONS_DIR" ]; then
    ADAPTATIONS_DIR="$PROJECT_DIR/adaptions"
fi

# if it doesn't exist, set it to the current canonical name:
if [ ! -d $ADAPTATIONS_DIR ]; then
    ADAPTATIONS_DIR="$PROJECT_DIR/a9s"
fi
if [ -z $LOCALDEFS ]; then
    LOCALDEFS="$ADAPTATIONS_DIR/common/calabash/localdefs.sh"
fi

DRIVER=Main
SCRIPT=$(basename "${BASH_SOURCE[0]}" .sh)
if [ -z $PORT ]; then
    PORT=8089
fi
if [ -z $EXPIRES ]; then
    EXPIRES=86400
fi

if [ $SCRIPT == piperack ]; then
    DRIVER=Piperack
    PIPERACK_PORT="--piperack-port $PORT --piperack-default-expires=$EXPIRES"
fi

if [ -f "$LOCALDEFS" ]; then
  echo Using local Calabash settings file "$LOCALDEFS" >&2
  source "$LOCALDEFS"
fi

if [ -z $HEAP ]; then
    HEAP=1024m
fi

if [ -z $UI_LANG ]; then
    UI_LANG=en
fi

if [ -z $CFG ]; then
    CFG=$EXT_BASE/transpect/transpect-config.xml
fi

**Comment by gimsieke** [comment]
I replaced `readlink -f` with `real_dir` in  93a095f

**Comment by mrchristian** [comment]
Hi,

Thank you so much. Cleared up that issue.

Now I have updated I no longer get the same issue, but I now get another 'file not found' error.

If I am running the same script on Ubuntu then there is no error.

Thanks

Simon

QUOTE

mrcs-MBP:epubtools-frontend mrchristian$ ./epubconvert epubtools/sample/sample.html
ERROR: input file not found: /Users/mrchristian/Documents/GitHub/epubtools-frontend/epubtools/sample

epubconvert

Usage: epubconvert [options ...] <file.html>

Options:
   -o    relative or absolute path to custom output directory
   -c    relative or absolute path to configuration file
   -f    format: 'EPUB2' | 'EPUB3' | 'KF8' // DEFAULT: 'EPUB2'
   -d    debug mode
mrcs-MBP:epubtools-frontend mrchristian$

**Comment by mrchristian** [comment]
Hi,

Ooops. What am I saying. When updating repo on Ubuntu I do get the same error.

Thanks

Simon

**Comment by gimsieke** [comment]
@mkraetke will look into this since I'm about to leave for the beach now.

**Comment by mrchristian** [comment]
Hi,

Thanks for all your help. Very much appreciated.

@mkraetke thanks.

I'm around working on sample files.

Simon

**Comment by mkraetke** [comment]
I've fixed some issues with this commit b328b694a60f299c3065ae8e0147137dfff937ec. I'll test it on OSX to ensure the script is working as expected.

**Comment by mrchristian** [comment]
Hi,

Works good on Ubuntu :-)

On OSX I get an error, but I think its related to JAVA, maybe I dont have right version or dependancies installed.

Errors says:

mrcs-MBP:epubtools-frontend mrchristian$ ./epubconvert epubtools/sample/sample.html
starting epubconvert
Errors encountered while running epubtools. Exited with code 1.
For details see epubtools/sample/sample.log
mrcs-MBP:epubtools-frontend mrchristian$ 

LOGS say:

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/xmlcalabash/drivers/Main : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

Thanks

Simon

**Comment by mkraetke** [comment]
You'll need at least Java 1.7. What is the output of `java -version`?

**Comment by mrchristian** [comment]
Hi,

This is my output. How do I upgrade the Java on OSX. Thanks

Simon

java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
mrcs-MBP:epubtools-frontend mrchristian$

**Comment by mkraetke** [comment]
Just head to the [Oracle Java Website](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html), download the latest JDK for Mac OS X and install the DMG.

**Comment by mrchristian** [comment]
Hi,

Super, it all works!!!

Success, eBooks creation now works on osx.

A million thank yous and I'll report back on the class.

Thanks again

Simon

**Comment by mkraetke** [comment]
You're welcome!
