### ISSUE TITLE
unsupported selector in rexcss3 parser?

### ISSUE THREAD

**Issue by peppobon** [transpect/epubtools-frontend#4]
Hi, 
we get the following css  parsing error:
ERROR: Underlying exception:
    lexical analysis failed
    while expecting ':'
    at line 1089, column 20:
    ...ease-in-out;
    }

when generating an epub with a css containing this selector:
button.sp-zoom:hover + img {
  max-height: max-content;
  max-width: 100%;
  transition: 0.3s ease-in-out;
}

Apparently the transition is not supported.
Is there an easy solution other than changing the source css?

Thanks,

__peppo

**Comment by gimsieke** [comment]
Maybe we only need to add `'s'` to `DIMENSION` in the [EBNF grammar](https://github.com/transpect/css-tools/blob/master/ebnf-scheme/CSS3.ebnf#L122) and recompile it to XSLT. I’ll try that.

**Comment by gimsieke** [comment]
Please update css-tools and try whether my fix works.

**Comment by peppobon** [comment]
Yes, it works!
As usual, thank you.
PS: your whole s/w stack is rock solid.

**Comment by gimsieke** [comment]
Thanks Peppo, that’s nice to hear!
